Fixed the bashrc file

diff --git a/chef/cookbooks/core/vdd/templates/default/bash/global.conf.erb b/chef/cookbooks/core/vdd/templates/default/bash/global.conf.erb
--- a/chef/cookbooks/core/vdd/templates/default/bash/global.conf.erb
+++ b/chef/cookbooks/core/vdd/templates/default/bash/global.conf.erb
@@ -44,28 +44,28 @@ PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
 if [ ! -e "$HOME/.sudo_as_admin_successful" ] && [ ! -e "$HOME/.hushlogin" ] ; then
     case " $(groups) " in *\ admin\ *)
     if [ -x /usr/bin/sudo ]; then
-  cat <<-EOF
-  To run a command as administrator (user "root"), use "sudo <command>".
-  See "man sudo_root" for details.
+        cat <<-EOF
+        To run a command as administrator (user "root"), use "sudo <command>".
+        See "man sudo_root" for details.
 
-  EOF
+        EOF
     fi
     esac
 fi
 
 # if the command-not-found package is installed, use it
 if [ -x /usr/lib/command-not-found -o -x /usr/share/command-not-found/command-not-found ]; then
-  function command_not_found_handle {
-          # check because c-n-f could've been removed in the meantime
+        function command_not_found_handle {
+                # check because c-n-f could've been removed in the meantime
                 if [ -x /usr/lib/command-not-found ]; then
-       /usr/lib/command-not-found -- "$1"
+                   /usr/lib/command-not-found -- "$1"
                    return $?
                 elif [ -x /usr/share/command-not-found/command-not-found ]; then
-       /usr/share/command-not-found/command-not-found -- "$1"
+                   /usr/share/command-not-found/command-not-found -- "$1"
                    return $?
-    else
-       printf "%s: command not found\n" "$1" >&2
-       return 127
-    fi
-  }
+                else
+                   printf "%s: command not found\n" "$1" >&2
+                   return 127
+                fi
+        }
 fi
